apiVersion: 1

datasources:
  - name: Health
    type: influxdb
    access: proxy
    database: health
    user: grafana
    password: grafana
    url: http://influxdb:8086
  - name: Instagram
    type: influxdb
    access: proxy
    database: instagram
    user: root
    password: root
    url: http://influxdb:8086
  - name: Trakt
    type: influxdb
    access: proxy
    database: trakt
    user: root
    password: root
    url: http://influxdb:8086
  - name: Github
    type: influxdb
    access: proxy
    database: github
    user: root
    password: root
    url: http://influxdb:8086        
  - name: Foursquare
    type: influxdb
    access: proxy
    database: foursquare
    user: root
    password: root
    url: http://influxdb:8086       
  - name: Gaming
    type: influxdb
    access: proxy
    database: gaming
    user: root
    password: root
    url: http://influxdb:8086
  - name: SMT
    type: influxdb
    access: proxy
    database: SMT
    user: tracks
    password: tracks
    url: http://influxdb:8086