{
 "title": "Instagram",
 "time": { "from": "now-6M", "to": "now" },
 "panels": [
  {
   "title": "Recent Instagram Posts",
   "type": "table",
   "gridPos": { "h": 20, "w": 14, "x": 0, "y": 0 },
   "targets": [
    {
     "limit": 10,
     "measurement": "post",
     "select": [
      [
       { "params": [ "thumbnail_html" ], "type": "field" }
      ],
      [
       { "params": [ "caption" ], "type": "field" }
      ],
      [
       { "params": [ "likes" ], "type": "field" }
      ],
      [
       { "params": [ "comments" ], "type": "field" }
      ],
      [
       { "params": [ "url" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Posts",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 14, "y": 0 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "measurement": "post",
     "select": [
      [
       { "params": [ "url" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Avg. Likes",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 16, "y": 0 },
   "format": "locale",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "post",
     "select": [
      [
       { "params": [ "likes" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Likes",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 0 },
   "format": "locale",
   "valueName": "total",
   "targets": [
    {
     "measurement": "post",
     "select": [
      [
       { "params": [ "likes" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Avg. Comments",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 0 },
   "format": "locale",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "post",
     "select": [
      [
       { "params": [ "comments" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Comments",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 0 },
   "format": "locale",
   "valueName": "total",
   "targets": [
    {
     "measurement": "post",
     "select": [
      [
       { "params": [ "comments" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Posts Per Week",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 2 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "alias": "Posts",
     "groupBy": [
      { "params": [ "1w" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "post",
     "select": [
      [
       { "params": [ "url" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Most Liked Post",
   "type": "table",
   "gridPos": { "h": 10, "w": 5, "x": 14, "y": 10 },
   "targets": [
    {
     "measurement": "post",
     "query": "SELECT top(likes,1) AS likes,thumbnail_html,url FROM (SELECT url,likes,thumbnail_html FROM post WHERE $timeFilter)",
     "select": [
      [
       { "params": [ "thumbnail_html" ], "type": "field" }
      ],
      [
       { "params": [ "caption" ], "type": "field" }
      ],
      [
       { "params": [ "likes" ], "type": "field" }
      ],
      [
       { "params": [ "comments" ], "type": "field" }
      ],
      [
       { "params": [ "url" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Most Commented On Post",
   "type": "table",
   "gridPos": { "h": 10, "w": 5, "x": 19, "y": 10 },
   "targets": [
    {
     "measurement": "post",
     "query": "SELECT top(comments,1) AS comments,thumbnail_html,url FROM (SELECT url,comments,thumbnail_html FROM post WHERE $timeFilter)",
     "select": [
      [
       { "params": [ "thumbnail_html" ], "type": "field" }
      ],
      [
       { "params": [ "caption" ], "type": "field" }
      ],
      [
       { "params": [ "likes" ], "type": "field" }
      ],
      [
       { "params": [ "comments" ], "type": "field" }
      ],
      [
       { "params": [ "url" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}